# https://golangci-lint.run/plugins/module-plugins/
version: v2.1.2
name: custom-golangci-lint
destination: bin
plugins:
  - module: 'github.com/cloverrose/mockguard'
    import: 'github.com/cloverrose/mockguard'
    version: v0.1.2
  - module: 'github.com/cloverrose/unusedinterface'
    import: 'github.com/cloverrose/unusedinterface'
    version: v0.2.5
  - module: 'github.com/cloverrose/pkgdep'
    import: 'github.com/cloverrose/pkgdep'
    version: v0.6.5
  - module: 'github.com/cloverrose/rpcguard'
    import: 'github.com/cloverrose/rpcguard'
    version: v0.6.1
  - module: 'github.com/cloverrose/connectnew'
    import: 'github.com/cloverrose/connectnew'
    version: v0.1.3
