version: "2"
linters:
  default: none
  enable:
    - mockguard
    - pkgdep
    - rpc_callvalidate
    - rpc_wraperr
    - unusedinterface
  settings:
    custom:
      mockguard:
        type: module
        description: check mockgen usage.
        settings:
          Content: //go:generate mockgen -source=$GOFILE -package=$GOPACKAGE --destination=mock_test.go
          FileName: types.go
      pkgdep:
        type: module
        description: pkgdep validates if package dependency follows rule.
        settings:
          config: ./.pkgdep.yaml
          inspector:
            file: ./out/used_rules.csv
          log:
            file: ./out/log.txt
            format: json
            level: DEBUG
      rpc_callvalidate:
        type: module
        description: check if RPC method uses Validate method properly.
        settings:
          log:
            file: ./out/rpc_callvalidate.log
            level: DEBUG
      rpc_wraperr:
        type: module
        description: check if RPC method returns wrapped error.
        settings:
          includePackages: github.com/cloverrose/linterplayground/.*
          log:
            file: ./out/rpc_wraperr.log
            level: DEBUG
          reportMode: RETURN
      unusedinterface:
        type: module
        description: unusedinterface find interface that are not used in their package
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unusedinterface
        path: internal/mockguard/ng_filename
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
