---
name: lint

on:
  pull_request:
  push:
    branches: [main]

# To cancel the previous run
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: go-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CI: true
  GOFLAGS: -mod=mod

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Aqua 1 # need to install Go before other packages.
        uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.38.0
          aqua_opts: "" # default option is 'l' that create links but skip downloading packages.
        env:
          AQUA_CONFIG: .aqua/aqua-go.yaml
      - run: go version
      - name: Install Aqua 2
        uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.38.0
          aqua_opts: "" # default option is 'l' that create links but skip downloading packages.
        env:
          AQUA_CONFIG: .aqua/aqua.yaml
      - name: Run lint tools
        run: |
          make lint
